### ISSUE TITLE
transformation des / en \ dans les url avec l'option fileName

### ISSUE THREAD

**Issue by jaar** [Giwi/camel-dav#2]
Si l'on utilise l'option fileName pour préciser un chemin vers le fichier à écrire, les "/" de l'url sont transformés en "\" ce qui entraîne une exception java.net.URISyntaxException: Illegal character in path. A noter que si on a un seul "/" l'erreur ne se produit pas.

ex :

from(FILE + "E://test/").to("dav://webstoreUrl/?fileName=${date:now:yyyyMMdd}/test/${file:onlyname}");

la log :

11:58:49.885 [Camel (camel-1) thread #196 - file://E://test/] INFO  org.giwi.camel.dav.DavOperations - buildDirectory : 20130124\attenteCIAHost, absolute : false
11:58:49.885 [Camel (camel-1) thread #196 - file://E://test/] INFO  org.giwi.camel.dav.DavOperations - buildDirectory : 20130124\attenteCIAHost/
11:58:49.885 [Camel (camel-1) thread #196 - file://E://test/] INFO  org.giwi.camel.dav.DavOperations - existsFile : 20130124\attenteCIAHost/
11:58:49.885 [Camel (camel-1) thread #196 - file://E://test/] WARN  o.giwi.camel.dav.RemoteFileProducer - Writing file failed with: null
11:58:49.885 [Camel (camel-1) thread #196 - file://E://test/] WARN  o.a.c.c.file.GenericFileOnCompletion - Rollback file strategy: org.apache.camel.component.file.strategy.GenericFileRenameProcessStrategy@a40050 for file: GenericFile[E:\test\test2.txt]
11:58:49.885 [Camel (camel-1) thread #196 - file://E://test/] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-M247-52485-1359025123593-0-9 on ExchangeId: ID-M247-52485-1359025123593-0-10). Exhausted after delivery attempt: 1 caught: java.lang.IllegalArgumentException
java.lang.IllegalArgumentException: null
    at java.net.URI.create(URI.java:842) ~[na:1.6.0_05]
    at org.apache.http.client.methods.HttpHead.<init>(HttpHead.java:72) ~[httpclient-4.1.jar:4.1]
    at com.googlecode.sardine.impl.SardineImpl.exists(SardineImpl.java:671) ~[sardine-314.jar:November 18 2011]
    at org.giwi.camel.dav.DavOperations.existsFile(DavOperations.java:67) ~[camel-sardine-0.0.1-SNAPSHOT.jar:na]
    at org.giwi.camel.dav.DavOperations.buildDirectory(DavOperations.java:101) ~[camel-sardine-0.0.1-SNAPSHOT.jar:na]
    at org.apache.camel.component.file.GenericFileProducer.writeFile(GenericFileProducer.java:238) ~[camel-core-2.10.1.jar:2.10.1]
    at org.apache.camel.component.file.GenericFileProducer.processExchange(GenericFileProducer.java:151) ~[camel-core-2.10.1.jar:2.10.1]
...
Caused by: java.net.URISyntaxException: Illegal character in path at index 34: http://webstore.url:8080//20130124\attenteCIAHost/
    at java.net.URI$Parser.fail(URI.java:2809) ~[na:1.6.0_05]

Avec 
from(FILE + "E://test/").to("dav://webstoreUrl/?fileName=test/${file:onlyname}");
on n'a pas d'exception

**Comment by jaar** [comment]
Il semble que le bug se produit si l'on envoie un fichier depuis Windows. Le séparateur pris est celui de Windows (\) alors que pour une url web on veut un séparateur /.

**Comment by Giwi** [comment]
Il faut que je me trouve un environnement de test sous Windows.

**Comment by Giwi** [comment]
Start working on it.

**Comment by Giwi** [comment]
fixed with 0.0.3-SNAPSHOT
